### ISSUE TITLE
The latest checker failed always

### ISSUE THREAD

**Issue by CrazyNash** [pingcap/tidb-tools#43]
I tried from several DBs, all failed for same error

```
2018/07/16 16:51:19 main.go:72: [fatal] create database connection failed: Error 1115: Unknown character set: 'utf8mb4'
```

When I check with a previous version downloaded from June, it completed successfully.

**Comment by WangXiangUSTC** [comment]
could you please provide your create database sql?

**Comment by CrazyNash** [comment]
@WangXiangUSTC  create database nash;

**Comment by IANTHEREAL** [comment]
@CrazyNash I have to close this issue, because we don't provide `checker` any more. 
 Now we only provide [`pre-check` feature in `DM`](https://pingcap.com/docs/tools/dm/manage-task/#precheck-the-upstream-mysql-instance-configuration), and the core code is in [check pkg](https://github.com/pingcap/tidb-tools/tree/master/pkg/check)
Later maybe we provide a separate binary for it
